utils: pass char * to strchr to not discard const qualifier
The twist type is defined as `const char*`. This causes current versions
of gcc (15.2.1 in my case) to generate the following warning:

  src/lib/utils.c: In function 'aes256_gcm_decrypt':
  src/lib/utils.c:243:17: error: initialization discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
    243 |     char *tag = strchr(objcopy, ':');
        |                 ^~~~~~
  cc1: all warnings being treated as errors

Most likely because gcc passes through the const qualifier to the strchr
output and the subsequent assignment to `tag` would remove it.

Use `iv` instead of `objcopy`, which points to the same memory but is
casted to remove the `const` qualifier.

Signed-off-by: Leonard Göhrs <l.goehrs@pengutronix.de>