test/nss-tests.sh: add missing files to cleanup
make distcheck fails with the below message. So add these files to the
cleanup list.

ERROR: files left in build directory after distclean:
./objdata
./objdata2
./noise.bin
./tpm2-client.csr.pem
./tpm2-client.csr.der
./tpm2-client.crt.der

Signed-off-by: Bill Roberts <bill.c.roberts@gmail.com>