db: avoid -Werror=format-truncation with GCC >= 7
Since commit 548c65c384e1b6628974e9a5eebf9fe7e9a9b488 GCC >= 7 produces
several warnings of the form

src/lib/db.c: In function ‘db_new.constprop’:
src/lib/db.c:1504:37: error: ‘%s’ directive output may be truncated writing 5 bytes into a region of size between 1 and 4096 [-Werror=format-truncation=]
 1504 |     snprintf(lockpath, PATH_MAX, "%s%s", path, ".lock");
      |                                     ^~         ~~~~~~~

Signed-off-by: Jonas Witschel <diabonas@gmx.de>