tpm2_ptool import: add passin parameter and forward it to tpm2_import
`tpm2_import` is able to directly decrypt encrypted private key files
when the password of the file is provided by parameter `--passin`.
Provide the same parameter to `tpm2_ptool import` in order to be able to
directly import OpenSSL private key files in a PKCS#11 token.

Here is an example of commands used to test this feature:

    $ cd tools
    $ ./tpm2_ptool init
    action: Created
    id: 1
    $ ./tpm2_ptool addtoken --pid=1 --label=test --userpin=XXXX --sopin=YYYY

    $ openssl genrsa -out /tmp/key-rsa-nopass.pem 2048
    $ ./tpm2_ptool import --label test --userpin XXXX --privkey /tmp/key-rsa-nopass.pem --algorithm rsa
    action: import
    private:
      CKA_ID: '31656232616131313464316365663533'
    public:
      CKA_ID: '31656232616131313464316365663533'

    $ openssl genrsa -passout pass:secret -out /tmp/key-rsa-pass.pem 2048
    $ ./tpm2_ptool import --label test --userpin XXXX --privkey /tmp/key-rsa-pass.pem --algorithm rsa --passin pass:secret
    action: import
    private:
      CKA_ID: '33653364656163643766333563343965'
    public:
      CKA_ID: '33653364656163643766333563343965'

    $ ./tpm2_ptool import --label test --userpin XXXX --privkey /tmp/key-rsa-pass.pem --algorithm rsa --passin pass:wrong
    command: tpm2_import -V -C /tmp/tmpwfkiaq6z/primary.handle -i /tmp/key-rsa-pass.pem -u /tmp/tmpwfkiaq6z/rvddcxzg.pub -r /tmp/tmpwfkiaq6z/gc8co7my.priv -p 699f20dca6aeb513f8ac947cfc7e7d37 -G rsa --passin pass:wrong
    Traceback (most recent call last):
      File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2_ptool.py", line 30, in <module>
        main()
      File "/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2_ptool.py", line 26, in main
        commandlet.init('A tool for manipulating the tpm2-pkcs11 database')
      File "/tpm2-pkcs11/tools/tpm2_pkcs11/command.py", line 102, in init
        commandlet.get()[d['which']](d)
      File "/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_keys.py", line 235, in __call__
        objects = super(ImportCommand, self).__call__(args)
      File "/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_keys.py", line 188, in __call__
        tertiarypriv, tertiarypub, tertiarypubdata = self.new_key_create(
      File "/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_keys.py", line 229, in new_key_create
        tertiarypriv, tertiarypub, tertiarypubdata = tpm2.importkey(
      File "/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2.py", line 287, in importkey
        raise RuntimeError("Could not execute tpm2_import: %s" %
    RuntimeError: Could not execute tpm2_import: b'INFO on line: "429"
    in file: "lib/files.c": Assuming tpm context file\n
    140036919434688:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:
    bad decrypt:crypto/evp/evp_enc.c:610:\n
    140036919434688:error:0906A065:PEM routines:PEM_do_header:bad decrypt:crypto/pem/pem_lib.c:461:\n
    ERROR on line: "1155" in file: "lib/tpm2_openssl.c": Reading PEM file "/tmp/key-rsa-pass.pem" failed\n
    ERROR on line: "259" in file: "tools/tpm2_tool.c": Unable to run tpm2_import\n'

    $ openssl ecparam -name prime256v1 -genkey -out /tmp/key-ec-nopass.pem
    $ ./tpm2_ptool import --label test --userpin XXXX --privkey /tmp/key-ec-nopass.pem --algorithm ecc
    action: import
    private:
      CKA_ID: '36643430373661316639616334306136'
    public:
      CKA_ID: '36643430373661316639616334306136'

    $ openssl ec -aes256 -passout pass:secret -in /tmp/key-ec-nopass.pem -out /tmp/key-ec-pass.pem
    $ ./tpm2_ptool import --label test --userpin XXXX --privkey /tmp/key-ec-pass.pem --algorithm ecc --passin pass:secret
    action: import
    private:
      CKA_ID: '62383162363864363366356666333330'
    public:
      CKA_ID: '62383162363864363366356666333330'

Signed-off-by: Nicolas Iooss <nicolas.iooss@ledger.fr>