C_Digest: return len when output hash is NULL
Fix a condition on 5.2 style returns in C_Digest where the output buffer
is NULL and the digestlen is greater than the expected hashlen and the
5.2 style reurn handling code wasn't being invoked. Update the tests to
cover this conditions.

This bug was discovered when running:
tpm2pkcs11-tool --test --login
ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:221:Fapi_List_Finish() FAPI not provisioned.
ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:81:Fapi_List() ErrorCode (0x00060034) Entities_List
ERROR: Listing FAPI token objects failed.
Using slot 0 with a present token (0x1)
Logging in to "label".
Please enter User PIN:
C_SeedRandom() and C_GenerateRandom():
  seems to be OK
Digests:
  all 4 digest functions seem to work
ERROR: Mechanism not supported, got: 0x210
  SHA-1: OK
ERROR: Mechanism not supported, got: 0x240
Segmentation fault (core dumped)

Fixes: #620

Signed-off-by: William Roberts <william.c.roberts@intel.com>