test_parser: check the right variable in test_config_parser_empty_seq
The function `test_config_parser_empty_seq` used the same variables as
the function `test_attr_parser_good`, which seems wrong.

This issue was found after the global variables were made `const`. Then
the compiler reported the following warnings.

    test/unit/test_parser.c:220:27: error:
    ‘_home_wcrobert_empty_seq_yaml_len’ defined but not used
    [-Werror=unused-const-variable=]
      220 | static const unsigned int _home_wcrobert_empty_seq_yaml_len = 1155;
          |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    test/unit/test_parser.c:121:28: error:
    ‘_home_wcrobert_empty_seq_yaml’ defined but not used
    [-Werror=unused-const-variable=]
      121 | static const unsigned char _home_wcrobert_empty_seq_yaml[] = {
          |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Using the right variables made the test fail for two reasons:

- There was a stray double-quote (`"`) at the end of
  `_home_wcrobert_empty_seq_yaml`.
- The result of `attr_list_get_count()` was incorrect.

Fix all these issues.

Signed-off-by: Nicolas Iooss <nicolas.iooss@ledger.fr>