ci: fix build with gcc not running plain build
The ocnditional checks were checking if CC == gcc, which is not valid
when:
  - CC is empty, which is a comon implication for configure to choose
gcc.
  - when gcc has the version number tacked onto it, like gcc-6.

Just check that CC != clang* and assume it's gcc and run a configure
without any options disabled and also perform the make distcheck to
make sure the release tarball doesn't break.

Now you'll also see errors during the build like:
../../src/lib/object.c:650:12: error: 'my_unused_func' defined but not used [-Werror=unused-function]
 static int my_unused_func(void) {
            ^

Fixes: #211

Signed-off-by: William Roberts <william.c.roberts@intel.com>