sign: fix hash_len type for 32 bit compilation
The wrong type causes errors for 32 bit builds of the form

src/lib/sign.c: In function 'sign_final_ex':
src/lib/sign.c:231:83: error: passing argument 4 of 'digest_final_op' from incompatible pointer type [-Werror=incompatible-pointer-types]
  231 |         rv = digest_final_op(ctx, opdata->digest_opdata, (CK_BYTE_PTR)digest_buf, &hash_len);
      |                                                                                   ^~~~~~~~~
      |                                                                                   |
      |                                                                                   size_t * {aka unsigned int *}
In file included from src/lib/sign.c:9:
src/lib/digest.h:35:107: note: expected 'CK_ULONG_PTR' {aka 'long unsigned int *'} but argument is of type 'size_t *' {aka 'unsigned int *'}
   35 | CK_RV digest_final_op(session_ctx *ctx, digest_op_data *supplied_opdata, CK_BYTE_PTR digest, CK_ULONG_PTR digest_len);
      |                                                                                              ~~~~~~~~~~~~~^~~~~~~~~~

Fixes: d80809ac3b8267f346f90bc3c73275bd8c66456e
Signed-off-by: Jonas Witschel <diabonas@gmx.de>