test_db: remove unused variables
Compilation with GCC 10.2.0 fails with

test/unit/test_db.c: In function ‘__wrap_sqlite3_finalize’:
test/unit/test_db.c:96:43: error: unused parameter ‘pStmt’ [-Werror=unused-parameter]
   96 | int __wrap_sqlite3_finalize(sqlite3_stmt *pStmt) {
      |                             ~~~~~~~~~~~~~~^~~~~
test/unit/test_db.c: In function ‘test_db_get_tokens_calloc_fail’:
test/unit/test_db.c:1141:16: error: unused variable ‘sobj’ [-Werror=unused-variable]
 1141 |     sealobject sobj = { 0 };
      |                ^~~~
test/unit/test_db.c: In function ‘test_db_get_tokens_sqlite3_prepare_v2_fail’:
test/unit/test_db.c:1159:16: error: unused variable ‘sobj’ [-Werror=unused-variable]
 1159 |     sealobject sobj = { 0 };
      |                ^~~~
test/unit/test_db.c: In function ‘test_db_get_tokens_token_overcount_fail’:
test/unit/test_db.c:1176:16: error: unused variable ‘sobj’ [-Werror=unused-variable]
 1176 |     sealobject sobj = { 0 };
      |                ^~~~
test/unit/test_db.c: In function ‘test_db_get_tokens_init_seal_objects_fail’:
test/unit/test_db.c:1203:16: error: unused variable ‘sobj’ [-Werror=unused-variable]
 1203 |     sealobject sobj = { 0 };
      |                ^~~~
test/unit/test_db.c: In function ‘test_db_get_tokens_init_tobjects_fail’:
test/unit/test_db.c:1238:16: error: unused variable ‘sobj’ [-Werror=unused-variable]
 1238 |     sealobject sobj = { 0 };
      |                ^~~~
test/unit/test_db.c: In function ‘test_db_update_for_pinchange_sqlite3_bind_private_blob_fail’:
test/unit/test_db.c:1358:73: error: unused parameter ‘state’ [-Werror=unused-parameter]
 1358 | void test_db_update_for_pinchange_sqlite3_bind_private_blob_fail(void **state) {
      |                                                                  ~~~~~~~^~~~~
test/unit/test_db.c: In function ‘test_db_update_for_pinchange_sqlite3_bind_public_blob_fail’:
test/unit/test_db.c:1413:11: error: unused variable ‘rv’ [-Werror=unused-variable]
 1413 |     CK_RV rv = db_update_for_pinchange(
      |           ^~
test/unit/test_db.c: In function ‘test_db_update_for_pinchange_sqlite3_bind_int_fail’:
test/unit/test_db.c:1450:11: error: unused variable ‘rv’ [-Werror=unused-variable]
 1450 |     CK_RV rv = db_update_for_pinchange(
      |           ^~
test/unit/test_db.c: In function ‘test_db_update_for_pinchange_sqlite3_step_fail’:
test/unit/test_db.c:1489:11: error: unused variable ‘rv’ [-Werror=unused-variable]
 1489 |     CK_RV rv = db_update_for_pinchange(
      |           ^~
test/unit/test_db.c: In function ‘test_db_update_for_pinchange_sqlite3_finalize_fail’:
test/unit/test_db.c:1528:11: error: unused variable ‘rv’ [-Werror=unused-variable]
 1528 |     CK_RV rv = db_update_for_pinchange(
      |           ^~
test/unit/test_db.c: In function ‘test_db_update_for_pinchange_commit_fail’:
test/unit/test_db.c:1567:11: error: unused variable ‘rv’ [-Werror=unused-variable]
 1567 |     CK_RV rv = db_update_for_pinchange(
      |           ^~

Signed-off-by: Jonas Witschel <diabonas@gmx.de>